### ISSUE TITLE
Research: Support conditional page snippets

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#102]
I'd like to have support for something like "conditional page snippets". Something kind of like what's available in some Google documentation:

![image](https://user-images.githubusercontent.com/7783288/28762574-a3e59ff2-7585-11e7-929e-d80642dd8e63.png)

https://cloud.google.com/storage/docs/authentication#storage-authentication-csharp

I would like for it to be possible in posts to have sections that change depending on the user's particular scenario, like one set of instructions for Windows and another set of instructions for OS X and the user would click a tab to see the instructions they want.

This extends beyond just code snippets, as I'd want prose text as well. A good example might be [Siacoin mining guide](https://mtlynch.io/windows-sia-mining/#install-gpu-library), where I'd like to only display instructions for CUDA or OpenCL depending on which GPU the user selects.

**Comment by shredtechular** [comment]
If I understand the task correctly, what we are really looking for here is tab functionality correct?  So, for example, if a user wants to see instructions for Windows, they click on the Windows tab.  If Linux, they click on Linux tab and the Linux instructions display.

I don't know of any plugins or built in solutions that will generate this tabbing behavior out of the box.  However, this is really just javascript showing/hiding different content sections.  The issue with Jekyll is getting certain sections within a post to generate in the correct format so the show/hiding and tabs renders in a nice way.

With any of the solutions below, we would need to create/import the js for the tabs, but I can think of the following solutions to generate the correct HTML structure:

## Jekyll collection for tabs
### Overview:
The idea here is to create a Jekyll collection where each item in the collection houses a different tab's content.
### Example of what it would look like in a post
```
{% include tabs.html tabs="windows-10,linux,macos-10-snow-leopard,macos-10-sierra" selected="linux" %}
```
### Pros
- very easy for a content writer to set up the tabs section in a post, but they must know the slug or id of the items in the collection they want to link to.
- can re-use the same item on multiple posts.  Not sure if this would ever be a scenario, but maybe some prose could be the same in multiple posts?
- all layout changes contained within an include partial
### Cons
- a separate area to put the actual content for a tab, so it could be confusing or more complex for a writer in that respect?

## Excerpt/Split functionality to break up content
### Overview:
The idea here is to use some type of unique identifier to break content into individual tabs.  The template would split out tabs in a post using that unique identifier such as `<!--tabs-->` and then loop through to setup the structure for a tabbing capability.
### Example of what it would sort of look like in a post...
```
<!--tabs-->
### Windows
Windows instructions for blah blah
<!--tabs-->
### Linux
Linux instructions for blah blah
<!--tabs-->
### MacOS
MacOS instructions for blah blah
```
### Pros
- all content is contained right within the post
### Cons
- would need to modify theme's article layout or introduce our own.
- having multiple tab sections within one post could be problematic.  I'm sure we can figure out a way to do it, but it would likely involve using yml frontmatter to setup different tab sections and linking them to the split out areas in a post.

## Use yml frontmatter
### Overview:
The idea here is to use yml frontmatter keys for setting up the required structure for tabbing capability.
### Example of what it would sort of look like in a post...
```
tabs:
  - tab-section: 
     - name: Instructions for OS installation
       - tab: 
          id: 1
          name: Windows
          type: prose
          content: "Windows instructions for blah blah"
       - tab:
          id: 2
          type: prose
          name: Linux
          content: "Linux instructions for blah blah"
  - tab-section:
     - name: Code examples for installation
       - tab:
          id: code1
          type: file
          name: Windows
          content: windows.sh
       - tab:
          id: code2
          type: file
          name: Linux
          content: linux.sh
```
### Pros
- all content is contained is within the post, yet in the yml
### Cons
- would need to modify theme's article layout or introduce our own.
- content is within yml and if the content is quite long for a given tab, it could be quite long and not very user friendly using pure markdown.
- again, I think using markdown in yml could get complex and problematic

## Write a plugin/custom tag
### Overview:
Obviously write a plugin that can take some specifically written content within a post and output a tabbing HTML structure.
### Pros
- Probably the cleanest solution and could dictate exactly how to write the structure within a post.
### Cons
- Very high level of effort and not sure I am actually the most qualified for doing this, but I think it would be an option.
