### ISSUE TITLE
Add Discuss button for reddit / Hacker News

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#185]
The blog post view has a sequence of social sharing buttons along the bottom:

![image](https://user-images.githubusercontent.com/7783288/32408923-9289a6ca-c177-11e7-836f-d35c5a3a150a.png)

I'd like to make it so that I can set frontmatter on a post to add links to associated threads on reddit or [Hacker News](https://news.ycombinator.com), like this:

```yaml
discuss_urls:
  reddit: https://www.reddit.com/r/CryptoCurrency/comments/6hm4w0/how_i_stole_your_siacoin/
  hacker_news: https://news.ycombinator.com/item?id=14568558
```

If `discuss_urls` is set, a row should appear below the social share buttons like this:

```
DISCUSS ON
[reddit] [Hacker News]
```

If `discuss_urls` is unset, it doesn't show anything (i.e., behavior like the current implementation).

If only one of the two URLs is set, it should show the button for just that site.
